version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/taskDB?sslmode=disable
    networks:
      - task-network

  # PostgreSQL service
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskDB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - task-network

# Define volumes
volumes:
  db-data:

# Define networks
networks:
  task-network:
    driver: bridge